In [1]:
import numpy as np

In [2]:
# 1D array
x=np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [3]:
print(x[0])   # 0 is index
print(x[2])

1.0
3.0


In [4]:
xmin=0.0
xmax=5.0
dx=0.5
x2=np.arange(xmin,xmax,dx)
print(x2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [5]:
n=len(x2)
print(n)

10


In [6]:
x3=np.zeros(10)
print(x3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
x4=np.zeros(10,dtype=int)
print(x4)

[0 0 0 0 0 0 0 0 0 0]


In [8]:
x4[2]=5   #  2 is index
print(x4)

[0 0 5 0 0 0 0 0 0 0]


In [9]:
# 2D array
y1=np.zeros((2,3))
print(y1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
y1[1,2]=3.4   # 1, 2 are indecies for 1st dim and 2nd dim
print(y1)

[[0.  0.  0. ]
 [0.  0.  3.4]]


In [11]:
print(y1.shape)

(2, 3)


In [12]:
y2=np.zeros((3,5))
for ix in np.arange(0,3,1):
    for iy in np.arange(0,5,1):
        print("ix=",ix,"   iy=",iy)
        y2[ix,iy]=ix*100+iy
        
print(y2)

ix= 0    iy= 0
ix= 0    iy= 1
ix= 0    iy= 2
ix= 0    iy= 3
ix= 0    iy= 4
ix= 1    iy= 0
ix= 1    iy= 1
ix= 1    iy= 2
ix= 1    iy= 3
ix= 1    iy= 4
ix= 2    iy= 0
ix= 2    iy= 1
ix= 2    iy= 2
ix= 2    iy= 3
ix= 2    iy= 4
[[  0.   1.   2.   3.   4.]
 [100. 101. 102. 103. 104.]
 [200. 201. 202. 203. 204.]]


In [13]:
# in above, ix is row number, iy column number

In [14]:
a=y2[2,3]
print(a)

203.0


In [15]:
# copy some elements
b=y2[0:2,1]
print(b)

[  1. 101.]


In [16]:
c=y2[:,2]
print(c)

[  2. 102. 202.]


In [17]:
# multiply
d=c*3.0
print(d)

[  6. 306. 606.]
